version: '1.0'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - '5001:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  fastapi:
    build: .
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_data: