"""Make entry_id column of Card table be nullable

Revision ID: 13df5f93aa8d
Revises: 8c0669703298
Create Date: 2024-06-04 20:38:16.634185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "13df5f93aa8d"
down_revision = "8c0669703298"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cards", "entry_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cards", "entry_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###
