"""Add column is_current_round to Set table

Revision ID: 0552e4715206
Revises: 67f238ff61ca
Create Date: 2024-06-04 19:39:19.195310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0552e4715206"
down_revision = "67f238ff61ca"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sets", sa.Column("trump_value", sa.Integer(), nullable=False)
    )
    op.add_column(
        "sets", sa.Column("is_current_round", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "sets", sa.Column("opening_player_id", sa.UUID(), nullable=False)
    )
    op.create_foreign_key(
        None,
        "sets",
        "users",
        ["opening_player_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sets", type_="foreignkey")
    op.drop_column("sets", "opening_player_id")
    op.drop_column("sets", "is_current_round")
    op.drop_column("sets", "trump_value")
    # ### end Alembic commands ###
