"""Fix FK leader relationship

Revision ID: bbc83de0c83e
Revises: d326664306c9
Create Date: 2024-06-02 14:44:48.704239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bbc83de0c83e"
down_revision = "d326664306c9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lobbies", sa.Column("leader_id", sa.UUID(), nullable=False))
    op.create_foreign_key(
        None, "lobbies", "users", ["leader_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "lobbies", type_="foreignkey")
    op.drop_column("lobbies", "leader_id")
    # ### end Alembic commands ###
