"""Add status to Friendship M2M table

Revision ID: 69039f97ff0f
Revises: 9f1037ed9cb0
Create Date: 2024-06-01 23:39:41.778597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "69039f97ff0f"
down_revision = "9f1037ed9cb0"
branch_labels = None
depends_on = None

friendship_status = postgresql.ENUM(
    "requested", "accepted", "declined", name="friendshipstatus"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    friendship_status.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "friendships",
        sa.Column(
            "status",
            friendship_status,
            nullable=False,
            server_default="requested",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("friendships", "status")
    # ### end Alembic commands ###
