"""Rename UserGame M2M tables

Revision ID: 31aa1e85847e
Revises: 2863bff86c88
Create Date: 2024-04-11 20:59:36.665662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "31aa1e85847e"
down_revision = "2863bff86c88"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
