"""Add round_number

Revision ID: ad3e1a953a69
Revises: d432a66c8e6e
Create Date: 2024-06-14 02:34:34.163114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad3e1a953a69'
down_revision = 'd432a66c8e6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sets', sa.Column('round_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sets', 'round_number')
    # ### end Alembic commands ###
