"""Add Lobby table

Revision ID: d326664306c9
Revises: 69039f97ff0f
Create Date: 2024-06-02 14:26:43.227630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d326664306c9"
down_revision = "69039f97ff0f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lobbies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lobbies_id"), "lobbies", ["id"], unique=False)
    op.create_table(
        "lobby_players",
        sa.Column("lobby_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lobby_id"], ["lobbies.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("lobby_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lobby_players")
    op.drop_index(op.f("ix_lobbies_id"), table_name="lobbies")
    op.drop_table("lobbies")
    # ### end Alembic commands ###
