"""Make trump columns of Set table be nullable

Revision ID: c6663e075bbb
Revises: 13df5f93aa8d
Create Date: 2024-06-04 20:41:38.832270

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c6663e075bbb"
down_revision = "13df5f93aa8d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sets",
        "trump_suit",
        existing_type=postgresql.ENUM("H", "D", "C", "S", name="suit"),
        nullable=True,
    )
    op.alter_column(
        "sets", "trump_value", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sets", "trump_value", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "sets",
        "trump_suit",
        existing_type=postgresql.ENUM("H", "D", "C", "S", name="suit"),
        nullable=False,
    )
    # ### end Alembic commands ###
