"""Add game tables

Revision ID: 67f238ff61ca
Revises: bbc83de0c83e
Create Date: 2024-06-02 23:05:05.192131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "67f238ff61ca"
down_revision = "bbc83de0c83e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "trump_suit",
            sa.Enum("hearts", "diamonds", "clubs", "spades", name="suit"),
            nullable=False,
        ),
        sa.Column("round_name", sa.String(), nullable=False),
        sa.Column("dealer_id", sa.UUID(), nullable=False),
        sa.Column("game_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dealer_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sets_id"), "sets", ["id"], unique=False)
    op.create_table(
        "dealings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("set_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["set_id"], ["sets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "set_id", name="_user_set_uc"),
    )
    op.create_index(op.f("ix_dealings_id"), "dealings", ["id"], unique=False)
    op.create_table(
        "entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("set_id", sa.UUID(), nullable=False),
        sa.Column("is_finished", sa.Boolean(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["set_id"], ["sets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_entries_id"), "entries", ["id"], unique=False)
    op.create_table(
        "cards",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column(
            "suit",
            sa.Enum("hearts", "diamonds", "clubs", "spades", name="suit"),
            nullable=False,
        ),
        sa.Column("dealing_id", sa.UUID(), nullable=False),
        sa.Column("entry_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dealing_id"], ["dealings.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"], ["entries.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cards_id"), "cards", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cards_id"), table_name="cards")
    op.drop_table("cards")
    op.drop_index(op.f("ix_entries_id"), table_name="entries")
    op.drop_table("entries")
    op.drop_index(op.f("ix_dealings_id"), table_name="dealings")
    op.drop_table("dealings")
    op.drop_index(op.f("ix_sets_id"), table_name="sets")
    op.drop_table("sets")
    # ### end Alembic commands ###
