"""Add `friendships` M2M table

Revision ID: 490eb180e512
Revises: 4c8efbaa554e
Create Date: 2024-04-01 22:32:31.120387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "490eb180e512"
down_revision = "4c8efbaa554e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "friendships",
        sa.Column("left_user_id", sa.UUID(), nullable=True),
        sa.Column("right_user_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["left_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["right_user_id"],
            ["users.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("friendships")
    # ### end Alembic commands ###
