"""Rename UserGame M2M tables

Revision ID: 9f1037ed9cb0
Revises: 31aa1e85847e
Create Date: 2024-04-11 21:03:57.349698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9f1037ed9cb0"
down_revision = "31aa1e85847e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
