"""Rename UserGame M2M tables

Revision ID: 2863bff86c88
Revises: d23ec9e1bd3c
Create Date: 2024-04-11 20:51:25.689034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2863bff86c88"
down_revision = "d23ec9e1bd3c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_players",
        sa.Column("game_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("game_id", "user_id"),
    )
    op.create_table(
        "game_winners",
        sa.Column("game_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("game_id", "user_id"),
    )
    op.drop_table("players")
    op.drop_table("winners")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "winners",
        sa.Column("game_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
            name="winners_game_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="winners_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("game_id", "user_id", name="winners_pkey"),
    )
    op.create_table(
        "players",
        sa.Column("game_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
            name="players_game_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="players_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("game_id", "user_id", name="players_pkey"),
    )
    op.drop_table("game_winners")
    op.drop_table("game_players")
    # ### end Alembic commands ###
