"""Add `elo` field to User model

Revision ID: 4c8efbaa554e
Revises: 546380025f3a
Create Date: 2024-03-27 16:03:23.565280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4c8efbaa554e"
down_revision = "546380025f3a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column("users", sa.Column("elo", sa.Integer(), nullable=True))
    op.execute("UPDATE users SET elo = 1000 WHERE elo IS NULL")
    op.alter_column("users", "elo", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "elo")
    # ### end Alembic commands ###
