"""Add actual_bid and score fields

Revision ID: e69243b08234
Revises: 75703d76f893
Create Date: 2025-06-14 18:08:59.048199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e69243b08234'
down_revision = '75703d76f893'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dealings', sa.Column('actual_bid', sa.Integer(), nullable=True))
    op.add_column('dealings', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dealings', 'score')
    op.drop_column('dealings', 'actual_bid')
    # ### end Alembic commands ###
